### ISSUE TITLE
Gltf 2.0 support

### ISSUE THREAD

**Issue by o-oualid** [EmbarkStudios/blender-tools#2]

**Comment by moppius** [comment]
Hi @o-oualid, thanks for opening this issue - we currently don't plan to support glTF until we are using that format in our own pipelines.

However, if someone else wants to add support for defining which import/export format to use, we'd consider Pull Requests for this feature.

It would also be useful if you could add some description to the issue so we have some context to understand how you'd like to use glTF in the add-on.

### Suggested Implementation
I'd suggest adding it as an option to the _Embark Add-on Preferences_, as an enum choice of **Game Export Format** with options for **FBX** and **glTF**, so that the setting is defined globally. This option would then be looked up at export time in order to pick the correct export path.
I suggest this method because we aim to use project-wide settings rather than case-by-case exports, and would like to avoid mixing formats wherever possible, so I'd prefer not allowing users to set it on an export-by-export basis.

**Comment by moppius** [comment]
Thanks to @GarmOfGnipahellir for taking the time to implement this, we now support choosing between FBX, GLTF and GLB format for exporting meshes. 🎉 

Here's how to do it:
1. In Blender, go to _Edit -> Preferences_
2. Go to the _Add-ons section_ and look for the _Generic: Embark Addon_ in the list
3. Change the **Export File Type** setting to your preference:
![image](https://user-images.githubusercontent.com/7034577/84593970-7e219180-ae4f-11ea-8f21-d557fc3013ef.png)
